name: CI/CD with Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    env:
      # These are loaded from GitHub Secrets for security
      server: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Start backend server (background)
        run: nohup npm start &
        working-directory: ./backend

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Install Keploy CLI
        run: curl --silent -L "https://keploy.io/ent/install.sh" | bash

      - name: Run Keploy tests
        run: keploy test --base-path http://localhost:4000
